cache:
  - '%HOMEDRIVE%%HOMEPATH%\.gradle\caches'
  - '%HOMEDRIVE%%HOMEPATH%\.gradle\wrapper\dists'

build_script:
  - gradlew assemble

test_script:
  - gradlew check

after_test:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $file = '.\build\test-results\test\TEST-edu.sc.seis.launch4j.Launch4jPluginExtensionTest.xml'
      (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path $file))

artifacts:
  - path: build\libs\*.jar
    name: Java archive
